"""The guard around `scripts/bump-version.sh`, the one command a release bump runs
before it commits a version.

The release workflow calls it with a word — `major`, `minor` or `patch` — reads the
version it moved to off its last line of stdout, and names the tag, the image and
the Release from that. What must hold:

1. **The version is computed from this repository's own manifest**, and the
   arithmetic is the one a release means: `0.5.1` + `minor` is `0.6.0`, `+ major`
   is `1.0.0`, `+ patch` is `0.5.2`, and a carry moves the higher parts
   (`1.9.9` + `minor` is `1.10.0`, `9.9.9` + `patch` is `9.9.10`).
2. **The version is the last line of stdout and the only line on stdout.**
   Anything else on that line is a tag named wrongly.
3. **Two files move and no others** *unless* `--page-sha` is given: `Cargo.toml`'s
   `[workspace.package] version` and `Cargo.lock`'s blocks for the local packages,
   the second regenerated by cargo so the two cannot disagree, and with
   `--page-sha` also `Dockerfile`'s `ARG WEB_CLIENT_SHA=` — the revision of
   `web_client` the page stage bakes, which the release resolves from that
   repository's latest release (`scripts/page-revision.sh`) and hands here. Given
   the revision the file already carries, `Dockerfile` is not written at all and
   the run says so. Everything else that names a number in prose — `README.md`
   here — is not this script's business.
4. **A word that is not one of the three is refused** — including the `X.Y.Z`
   form this used to take — as is a manifest whose version is not a plain `X.Y.Z`
   (fewer than three parts, a prerelease, a leading zero) because there is no next
   version to compute from it, a `--page-sha` that is not 40 lowercase hex
   characters (the empty string included: a caller that meant to name a revision
   and has none is the failure this option closes), and a `Dockerfile` without
   exactly one `ARG WEB_CLIENT_SHA=` line. Nothing is written for any of them.
5. **`--dry-run` prints the version and writes nothing**, so a caller can compute
   the tag before it decides to cut it.
6. **A failed run leaves the tree it started with.** A cargo that refuses, or one
   that leaves the lock disagreeing with the manifest, restores both files.

`cargo` is reached through `PATH`, so the tests put a stand-in there that does what
`cargo update --workspace` does — move the local packages in the lock to the
manifest's version — and records that it was asked. That is also how a dry run is
proved not to have run cargo at all. No test needs a toolchain, a network or this
repository's own manifests; each one builds the tree it means to test.

Run it directly:

    python3 -B scripts/test_bump_version.py

or as the flake check the workflows run: `nix build .#checks.<system>.bump-version`.
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPT = HERE / "bump-version.sh"
BASH = shutil.which("bash") or "/bin/bash"

# The `web_client` revision the image bakes, and the one a bump moves it to. Both
# are values this script may only carry: the first every test below asserts comes
# through untouched when `--page-sha` is not given, the second is what the release
# resolved from `web_client`'s latest release.
PAGE_SHA = "ecd07aa5daabdcc224f892784202b156b4c5f6a7"
NEW_PAGE_SHA = "0123456789abcdef0123456789abcdef01234567"

MANIFEST = """\
[workspace]
resolver = "3"
members = [
    "crates/protocol",
    "crates/selvaged",
]

[workspace.package]
version = "{version}"
edition = "2024"

[workspace.dependencies]
serde = {{ version = "1", features = ["derive"] }}
"""

# `serde` is a decoy: a registry package's version is not the workspace's, and a
# lock rewrite that moved every block would move this one too.
LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "selvage-protocol"
version = "{version}"

[[package]]
name = "selvaged"
version = "{version}"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "{checksum}"
"""

DOCKERFILE = """\
ARG VERSION=dev
ARG WEB_CLIENT_SHA={sha}

FROM builder AS page
ARG WEB_CLIENT_SHA
RUN echo "$WEB_CLIENT_SHA"
"""

README = """\
# Reference server

`v0.5.1` is the release this tree is at, and the page it serves is cut from
`web_client` at {sha}. Neither string is a home for a value.
"""

# What `cargo update --workspace` does to this workspace, and the whole of what
# the script may ask of cargo. Anything else fails, so a test that sees this run
# where it should not have knows.
STUB_CARGO = '''\
#!/usr/bin/env python3
import os
import re
import sys

log = os.environ.get("STUB_CARGO_LOG")
if log:
    with open(log, "a", encoding="utf-8") as handle:
        handle.write(" ".join(sys.argv[1:]) + "\\n")

if os.environ.get("STUB_CARGO_STATUS"):
    sys.exit(int(os.environ["STUB_CARGO_STATUS"]))

if sys.argv[1:2] != ["update"] or "--workspace" not in sys.argv:
    print("stub cargo implements `update --workspace` and nothing else", file=sys.stderr)
    sys.exit(1)

manifest = open("Cargo.toml", encoding="utf-8").read()
section = manifest.split("[workspace.package]", 1)[1]
version = os.environ.get("STUB_CARGO_LOCK_VERSION") or re.search(
    r'^version = "(.*)"$', section, re.MULTILINE
).group(1)

blocks = open("Cargo.lock", encoding="utf-8").read().split("[[package]]")
moved = []
for index, block in enumerate(blocks):
    if index and "source = " not in block:
        block = re.sub(r'(?m)^version = ".*"$', f'version = "{version}"', block)
    moved.append(block)
open("Cargo.lock", "w", encoding="utf-8").write("[[package]]".join(moved))
'''


class Repo:
    """A tree with the manifests, a stand-in cargo on PATH, and a snapshot."""

    def __init__(self, root: Path, version: str = "0.5.1"):
        self.root = root
        self.repo = root / "repo"
        self.bin = root / "bin"
        self.log = root / "cargo.log"
        (self.repo / "scripts").mkdir(parents=True)
        self.bin.mkdir()
        shutil.copy(SCRIPT, self.repo / "scripts" / SCRIPT.name)
        self.write(version)
        self.before = self.snapshot()
        stub = self.bin / "cargo"
        # The stand-in is executed by the script through `PATH`, so its shebang
        # has to name this interpreter rather than `/usr/bin/env`, which a nix
        # build sandbox does not have.
        stub.write_text(f"#!{sys.executable}\n" + STUB_CARGO.split("\n", 1)[1], encoding="utf-8")
        stub.chmod(0o755)

    def write(self, version: str) -> None:
        (self.repo / "Cargo.toml").write_text(MANIFEST.format(version=version), encoding="utf-8")
        (self.repo / "Cargo.lock").write_text(
            LOCK.format(version=version, checksum="a" * 64), encoding="utf-8"
        )
        (self.repo / "Dockerfile").write_text(DOCKERFILE.format(sha=PAGE_SHA), encoding="utf-8")
        (self.repo / "README.md").write_text(README.format(sha=PAGE_SHA), encoding="utf-8")

    def reset(self) -> None:
        """Re-take the snapshot a refusal has to be compared against."""
        self.before = self.snapshot()

    def snapshot(self) -> dict:
        """Every path under the tree, and what a file there holds."""
        taken = {}
        for path in sorted(self.repo.rglob("*")):
            relative = str(path.relative_to(self.repo))
            taken[relative] = path.read_bytes() if path.is_file() else None
        return taken

    def run(self, *arguments, **environment):
        env = dict(os.environ)
        env["PATH"] = f"{self.bin}:{env['PATH']}"
        env["STUB_CARGO_LOG"] = str(self.log)
        env.update(environment)
        # Run through the shell that the shebang names rather than by the shebang:
        # a nix build sandbox has no `/usr/bin/env`, and what the installed name
        # needs is the exec bit and that line, which the last test asserts.
        return subprocess.run(
            [BASH, str(self.repo / "scripts" / SCRIPT.name), *arguments],
            cwd=self.repo,
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )

    def cargo_ran(self) -> bool:
        return self.log.exists() and self.log.read_text(encoding="utf-8") != ""

    def read(self, name: str) -> str:
        return (self.repo / name).read_text(encoding="utf-8")

    def carries(self, version: str) -> bool:
        """Whether both homes of the version carry it, and only the local packages moved."""
        section = self.read("Cargo.toml").split("[workspace.package]", 1)[1]
        manifest = re.search(r'(?m)^version = "(.*)"$', section).group(1)
        members = [
            re.search(r'(?m)^version = "(.*)"$', block).group(1)
            for block in self.read("Cargo.lock").split("[[package]]")[1:]
            if "source = " not in block
        ]
        return manifest == version and members == [version, version]

    def declared(self) -> str:
        """What the manifest says, read the way a reviewer would."""
        section = self.read("Cargo.toml").split("[workspace.package]", 1)[1]
        return re.search(r'(?m)^version = "(.*)"$', section).group(1)


class ArgumentRefusalTest(unittest.TestCase):
    """Exit 2: the arguments are not ones this takes. Nothing is written."""

    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.repo = Repo(Path(self.directory.name))

    def assert_refused(self, arguments, says):
        done = self.repo.run(*arguments)
        self.assertEqual(done.returncode, 2, f"{arguments}: {done.stdout}{done.stderr}")
        self.assertIn("usage:", done.stderr)
        if says is not None:
            self.assertIn(says, done.stderr)
        self.assertEqual(self.repo.snapshot(), self.repo.before, "a refusal wrote to the tree")
        self.assertFalse(self.repo.cargo_ran(), "a refusal reached cargo")
        return done

    def test_a_word_that_is_not_one_of_the_three_is_refused(self):
        for word in ("1.2.3", "v0.5.1", "0.6.0", "Major", "MAJOR", "major ", "patchy", "0", "latest", "1.2.3-rc1", "minor.1", "minor,", "min"):
            with self.subTest(word=word):
                self.assert_refused([word], "not a bump word")

    def test_no_word_at_all_is_refused(self):
        self.assert_refused([], "no bump word given")

    def test_a_second_word_is_refused(self):
        self.assert_refused(["minor", "patch"], "more than one bump word")

    def test_an_unknown_option_is_refused(self):
        for option in ("--force", "--dry_run", "-n", "--page-sha=" + PAGE_SHA, "--page-sha=1", "--dry-run=1"):
            with self.subTest(option=option):
                self.assert_refused([option, "minor"], "unknown option")

    def test_a_page_sha_that_is_not_a_commit_is_refused(self):
        for sha in ("", "not-a-sha", PAGE_SHA[:-1], PAGE_SHA + "0", PAGE_SHA.upper(), " " + PAGE_SHA, "0" * 39):
            with self.subTest(sha=sha):
                self.assert_refused(["minor", "--page-sha", sha], "not 40 lowercase hex characters")

    def test_a_page_sha_without_a_value_is_refused(self):
        self.assert_refused(["minor", "--page-sha"], "--page-sha needs a value")

    def test_a_page_sha_given_twice_is_refused(self):
        self.assert_refused(["minor", "--page-sha", PAGE_SHA, "--page-sha", NEW_PAGE_SHA], "--page-sha is given twice")

    def test_dry_run_twice_is_refused(self):
        self.assert_refused(["minor", "--dry-run", "--dry-run"], "--dry-run is given twice")

    def test_an_empty_word_is_refused(self):
        self.assert_refused([""], "no bump word given")


class TreeRefusalTest(unittest.TestCase):
    """Exit 1: the tree is not one a version can be computed from. Nothing is written."""

    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.repo = Repo(Path(self.directory.name))

    def assert_refused(self, says, **environment):
        done = self.repo.run("minor", **environment)
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn(says, done.stderr)
        self.assertEqual(self.repo.snapshot(), self.repo.before, "a refusal wrote to the tree")
        self.assertFalse(self.repo.cargo_ran(), "a refusal reached cargo")
        return done

    def refused_version(self, version: str, word: str = "minor"):
        """A tree at `version` refuses `word` itself, and writes nothing doing it."""
        with tempfile.TemporaryDirectory() as directory:
            repo = Repo(Path(directory), version=version)
            done = repo.run(word)
            self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
            self.assertIn("which is not a plain MAJOR.MINOR.PATCH", done.stderr)
            # The refusal has to be the script's own reading of the manifest, not
            # bash dying on an unset `BASH_REMATCH` behind it.
            self.assertNotIn("unbound variable", done.stderr, "a bash diagnostic is not a refusal")
            self.assertEqual(repo.snapshot(), repo.before, "a refusal wrote to the tree")
            self.assertFalse(repo.cargo_ran(), "a refusal reached cargo")
            return done

    def test_a_manifest_version_with_fewer_than_three_parts_is_refused(self):
        for version in ("0.5", "1", "", "0.5.x", "1.x.0"):
            with self.subTest(version=version):
                self.refused_version(version)

    def test_a_manifest_version_that_is_not_a_plain_x_y_z_is_refused(self):
        for version in ("1.2.3.4", "1.2.3-rc1", "01.2.3", "1.02.3", "1.2.03", "v1.2.3", "1.2.3+build", " 1.2.3"):
            with self.subTest(version=version):
                self.refused_version(version, word="patch")

    def test_a_manifest_without_one_version_line_is_refused(self):
        text = MANIFEST.format(version="0.5.1")
        for replacement, count in (("", "0"), ('version = "0.5.1"\nversion = "0.5.1"\n', "2")):
            with self.subTest(count=count), tempfile.TemporaryDirectory() as directory:
                repo = Repo(Path(directory))
                manifest = repo.repo / "Cargo.toml"
                manifest.write_text(text.replace('version = "0.5.1"\n', replacement), encoding="utf-8")
                repo.reset()
                done = repo.run("minor")
                self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
                self.assertIn(f"has {count} top-level version lines", done.stderr)
                self.assertEqual(repo.snapshot(), repo.before, "a refusal wrote to the tree")
                self.assertFalse(repo.cargo_ran(), "a refusal reached cargo")

    def test_a_missing_manifest_or_lock_is_refused(self):
        for name in ("Cargo.toml", "Cargo.lock"):
            with self.subTest(name=name), tempfile.TemporaryDirectory() as directory:
                repo = Repo(Path(directory))
                (repo.repo / name).unlink()
                repo.reset()
                done = repo.run("major")
                self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
                self.assertIn(f"{name} is not there", done.stderr)
                self.assertFalse(repo.cargo_ran())

    def test_a_dockerfile_with_no_single_page_pin_is_refused_when_one_is_named(self):
        """`--page-sha` needs the one line it writes, and only when it is given."""
        for replacement, found in (("", "0"), (f"ARG WEB_CLIENT_SHA={PAGE_SHA}\nARG WEB_CLIENT_SHA={PAGE_SHA}\n", "2")):
            with self.subTest(found=found), tempfile.TemporaryDirectory() as directory:
                repo = Repo(Path(directory))
                dockerfile = repo.repo / "Dockerfile"
                dockerfile.write_text(
                    DOCKERFILE.format(sha=PAGE_SHA).replace(f"ARG WEB_CLIENT_SHA={PAGE_SHA}\n", replacement),
                    encoding="utf-8",
                )
                repo.reset()
                done = repo.run("minor", "--page-sha", NEW_PAGE_SHA)
                self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
                self.assertIn(f"has {found} ARG WEB_CLIENT_SHA= lines", done.stderr)
                self.assertEqual(repo.snapshot(), repo.before, "a refusal wrote to the tree")
                self.assertFalse(repo.cargo_ran())
                # The same tree without the option has no reason to look: nothing
                # else it writes is the page revision.
                self.assertEqual(repo.run("minor").returncode, 0)

    def test_a_missing_dockerfile_is_refused_only_when_a_page_sha_is_named(self):
        with tempfile.TemporaryDirectory() as directory:
            repo = Repo(Path(directory))
            (repo.repo / "Dockerfile").unlink()
            repo.reset()
            done = repo.run("minor", "--page-sha", NEW_PAGE_SHA)
            self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
            self.assertIn("Dockerfile is not there", done.stderr)
            self.assertEqual(repo.snapshot(), repo.before, "a refusal wrote to the tree")
            self.assertFalse(repo.cargo_ran())
            self.assertEqual(repo.run("minor").returncode, 0)

    def test_a_host_with_neither_cargo_nor_nix_is_refused(self):
        """The script says which toolchain it cannot reach rather than dying obscurely."""
        bare = self.repo.root / "bare-bin"
        bare.mkdir()
        for name in ("awk", "cp", "dirname", "grep", "head", "mkdir", "mv", "rm", "rmdir", "sed"):
            found = shutil.which(name)
            self.assertIsNotNone(found, name)
            (bare / name).symlink_to(found)
        done = self.repo.run("minor", PATH=str(bare))
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn("no cargo on PATH and no nix", done.stderr)
        self.assertEqual(self.repo.snapshot(), self.repo.before)

    def test_a_root_release_bumps_its_major(self):
        """`1.2.3` is a plain version; it is the *word* `1.2.3` that is not a bump."""
        (self.repo.repo / "Cargo.toml").write_text(MANIFEST.format(version="1.2.3"), encoding="utf-8")
        (self.repo.repo / "Cargo.lock").write_text(LOCK.format(version="1.2.3", checksum="a" * 64), encoding="utf-8")
        self.repo.reset()
        done = self.repo.run("major")
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(done.stdout.splitlines()[-1], "2.0.0")


class DryRunTest(unittest.TestCase):
    """`--dry-run` computes the version and writes nothing at all."""

    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.repo = Repo(Path(self.directory.name))

    def test_each_word_computes_its_version_and_writes_nothing(self):
        for word, expected in (("major", "1.0.0"), ("minor", "0.6.0"), ("patch", "0.5.2")):
            with self.subTest(word=word):
                before = self.repo.snapshot()
                done = self.repo.run(word, "--dry-run")
                self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
                self.assertEqual(done.stdout.splitlines()[-1], expected)
                self.assertEqual(self.repo.snapshot(), before, "a dry run wrote to the tree")
                self.assertFalse(self.repo.cargo_ran(), "a dry run reached cargo")

    def test_the_carry_cases_roll_the_higher_parts_over(self):
        for version, word, expected in (
            ("0.5.1", "minor", "0.6.0"),
            ("0.5.1", "major", "1.0.0"),
            ("0.5.1", "patch", "0.5.2"),
            ("1.9.9", "minor", "1.10.0"),
            ("1.9.9", "major", "2.0.0"),
            ("9.9.9", "patch", "9.9.10"),
            ("1.2.9", "major", "2.0.0"),
            ("0.0.1", "patch", "0.0.2"),
            ("10.20.30", "minor", "10.21.0"),
            ("0.0.0", "patch", "0.0.1"),
        ):
            with self.subTest(version=version, word=word), tempfile.TemporaryDirectory() as directory:
                repo = Repo(Path(directory), version=version)
                done = repo.run(word, "--dry-run")
                self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
                self.assertEqual(done.stdout.splitlines()[-1], expected, done.stdout)
                self.assertEqual(repo.snapshot(), repo.before)

    def test_the_option_comes_before_or_after_the_word(self):
        first = self.repo.run("--dry-run", "minor")
        second = self.repo.run("minor", "--dry-run")
        for done in (first, second):
            self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
            self.assertEqual(done.stdout.splitlines()[-1], "0.6.0")


class WriteTest(unittest.TestCase):
    """Without `--dry-run`, exactly two files move and the version is the last line."""

    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.repo = Repo(Path(self.directory.name))

    def bump(self, word):
        before = self.repo.snapshot()
        done = self.repo.run(word)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        return before, done

    def test_each_word_moves_the_two_files_and_nothing_else(self):
        for word, expected in (("major", "1.0.0"), ("minor", "0.6.0"), ("patch", "0.5.2")):
            with self.subTest(word=word), tempfile.TemporaryDirectory() as directory:
                repo = Repo(Path(directory))
                before = repo.snapshot()
                done = repo.run(word)
                self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
                self.assertEqual(done.stdout.splitlines()[-1], expected)
                self.assertIn("changed: Cargo.toml", done.stderr)
                self.assertIn("changed: Cargo.lock", done.stderr)
                self.assertTrue(repo.carries(expected), repo.read("Cargo.lock"))
                self.assertTrue(repo.cargo_ran())
                after = repo.snapshot()
                self.assertEqual(sorted(after), sorted(before))
                moved = {name for name in before if before[name] != after[name]}
                self.assertEqual(moved, {"Cargo.toml", "Cargo.lock"})
                self.assertIn(f"ARG WEB_CLIENT_SHA={PAGE_SHA}", repo.read("Dockerfile"))
                self.assertEqual(repo.read("README.md"), README.format(sha=PAGE_SHA))

    def test_the_prose_and_the_page_pin_are_not_this_script_s_business_unless_named(self):
        """Without `--page-sha` nothing about the page moves, prose included."""
        dockerfile = self.repo.read("Dockerfile")
        self.assertIn(f"ARG WEB_CLIENT_SHA={PAGE_SHA}", dockerfile)
        before, done = self.bump("minor")
        self.assertEqual(self.repo.read("Dockerfile"), dockerfile)
        self.assertNotIn("Dockerfile", done.stderr, "a run that was not asked to pin the page names no file")
        self.assertEqual(self.repo.read("README.md"), README.format(sha=PAGE_SHA))
        self.assertEqual(
            {name for name in before if before[name] != self.repo.snapshot()[name]},
            {"Cargo.toml", "Cargo.lock"},
        )

    def test_the_page_revision_moves_when_it_is_named(self):
        done = self.repo.run("minor", "--page-sha", NEW_PAGE_SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(done.stdout.splitlines(), ["0.6.0"])
        self.assertTrue(self.repo.carries("0.6.0"))
        self.assertIn(f"ARG WEB_CLIENT_SHA={NEW_PAGE_SHA}", self.repo.read("Dockerfile"))
        self.assertIn("changed: Dockerfile", done.stderr.splitlines())
        self.assertNotIn(f"ARG WEB_CLIENT_SHA={PAGE_SHA}\n", self.repo.read("Dockerfile"))

    def test_the_page_revision_is_the_only_other_line_that_moves(self):
        before = self.repo.read("Dockerfile").splitlines()
        done = self.repo.run("patch", "--page-sha", NEW_PAGE_SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        after = self.repo.read("Dockerfile").splitlines()
        self.assertEqual(len(after), len(before), "the file gained or lost a line")
        moved = [old for old, new in zip(before, after) if old != new]
        self.assertEqual(moved, [f"ARG WEB_CLIENT_SHA={PAGE_SHA}"])
        self.assertEqual(self.repo.read("README.md"), README.format(sha=PAGE_SHA))

    def test_a_page_revision_the_tree_already_carries_is_not_written(self):
        before = self.repo.snapshot()
        done = self.repo.run("minor", "--page-sha", PAGE_SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertTrue(any(line.startswith("unchanged: Dockerfile") for line in done.stderr.splitlines()), done.stderr)
        self.assertFalse(any(line.startswith("changed: Dockerfile") for line in done.stderr.splitlines()), done.stderr)
        after = self.repo.snapshot()
        self.assertEqual(self.repo.read("Dockerfile"), DOCKERFILE.format(sha=PAGE_SHA))
        self.assertEqual({name for name in before if before[name] != after[name]}, {"Cargo.toml", "Cargo.lock"})

    def test_the_option_comes_before_or_after_the_word(self):
        for arguments in (("--page-sha", NEW_PAGE_SHA, "minor"), ("minor", "--page-sha", NEW_PAGE_SHA)):
            with self.subTest(arguments=arguments), tempfile.TemporaryDirectory() as directory:
                repo = Repo(Path(directory))
                done = repo.run(*arguments)
                self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
                self.assertEqual(done.stdout.splitlines(), ["0.6.0"])
                self.assertIn(f"ARG WEB_CLIENT_SHA={NEW_PAGE_SHA}", repo.read("Dockerfile"))

    def test_the_version_is_the_last_line_of_stdout_and_the_only_one(self):
        for word, expected in (("major", "1.0.0"), ("minor", "0.6.0"), ("patch", "0.5.2")):
            with self.subTest(word=word), tempfile.TemporaryDirectory() as directory:
                repo = Repo(Path(directory))
                done = repo.run(word)
                self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
                self.assertEqual(done.stdout.splitlines(), [expected], "stdout is the version's line")

    def test_the_registry_package_in_the_lock_does_not_move(self):
        self.bump("minor")
        self.assertIn('name = "serde"\nversion = "1.0.219"', self.repo.read("Cargo.lock"))

    def test_a_second_bump_computes_from_the_version_the_first_one_wrote(self):
        self.bump("patch")
        self.assertEqual(self.repo.declared(), "0.5.2")
        _, done = self.bump("patch")
        self.assertEqual(done.stdout.splitlines()[-1], "0.5.3")
        self.assertTrue(self.repo.carries("0.5.3"))

    def test_a_cargo_that_fails_leaves_the_tree_it_started_with(self):
        before = self.repo.snapshot()
        done = self.repo.run("minor", STUB_CARGO_STATUS="1")
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn("cargo update --workspace failed", done.stderr)
        self.assertEqual(self.repo.snapshot(), before, "a failed cargo left a bumped tree")
        self.assertTrue(self.repo.cargo_ran())

    def test_a_cargo_that_leaves_the_lock_wrong_is_refused_and_the_tree_restored(self):
        before = self.repo.snapshot()
        done = self.repo.run("minor", STUB_CARGO_LOCK_VERSION="0.5.1")
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn("Cargo.lock does not carry 0.6.0", done.stderr)
        self.assertEqual(self.repo.snapshot(), before)

    def test_a_failure_after_the_page_revision_was_written_restores_it_too(self):
        before = self.repo.snapshot()
        done = self.repo.run("minor", "--page-sha", NEW_PAGE_SHA, STUB_CARGO_STATUS="1")
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn("cargo update --workspace failed", done.stderr)
        self.assertEqual(self.repo.snapshot(), before, "a failed run left a repinned Dockerfile")

    def test_the_work_directory_it_used_is_not_left_behind(self):
        before = self.repo.snapshot()
        self.bump("minor")
        self.assertNotIn(".tmp", self.repo.snapshot())
        self.assertEqual(sorted(self.repo.snapshot()), sorted(before))


class InstallationTest(unittest.TestCase):
    """The script is run as a program, so the tracked file is executable."""

    def test_the_script_is_executable_and_has_a_shebang(self):
        self.assertTrue(os.access(SCRIPT, os.X_OK), SCRIPT)
        self.assertEqual(SCRIPT.read_bytes().split(b"\n", 1)[0], b"#!/usr/bin/env bash")


if __name__ == "__main__":
    unittest.main(verbosity=2)
