"""The guard around `scripts/bump-version.sh`, the one command the release
coordinator runs before it commits a version.

The coordinator computes a next version, hands it here with the `web_client`
revision the image bakes, and commits what this changed. What must hold:

1. **The two values are the only thing it moves, and only where they live.** The
   three files it may write are `Cargo.toml`'s `[workspace.package] version`,
   `Cargo.lock`'s blocks for the local packages, and `Dockerfile`'s one
   `ARG WEB_CLIENT_SHA=` line. Prose that happens to name a version is not a home
   for it, and a file whose value is already right is not rewritten.
2. **A version that is not `X.Y.Z`, and a sha that is not 40 lowercase hex, are
   refused before anything is written** — including the empty and the
   `v`-prefixed and the prerelease forms, which are the shapes a hand-written
   release bump gets wrong.
3. **`--page-sha` is required**, because a release that built a page has a
   revision and a caller that omits it would ship the previous one.
4. **A tree that already carries both values is a no-op and exit 0.**
5. **A failed run leaves the tree it started with.** The lock is regenerated by
   cargo, and cargo failing must not leave a bumped manifest and a stale lock for
   someone to commit.

`cargo` is reached through `PATH`, so the tests put a stand-in there that does
what `cargo update --workspace` does — move the local packages in the lock to the
manifest's version — and records that it was asked. That is also how a no-op is
proved not to have run cargo at all. No test needs a toolchain, a network or this
repository's own manifests; each one builds the tree it means to test.

Run it directly:

    python3 scripts/test_bump_version.py

or as the flake check the workflows run: `nix build .#checks.<system>.bump-version`.
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPT = HERE / "bump-version.sh"

BASH = shutil.which("bash") or "/bin/bash"

SHA = "d1bdb1161699c0289a46bf803d68b9a78f27b573"
OTHER_SHA = "ecd07aa5daabdcc224f892784202b156b4c5f6a7"

MANIFEST = """\
[workspace]
resolver = "3"
members = [
    "crates/protocol",
    "crates/selvaged",
]

[workspace.package]
version = "{version}"
edition = "2024"

[workspace.dependencies]
serde = {{ version = "1", features = ["derive"] }}
"""

# `serde` is a decoy: a registry package's version is not the workspace's, and a
# lock rewrite that moved every block would move this one too.
LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "selvage-protocol"
version = "{version}"

[[package]]
name = "selvaged"
version = "{version}"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "{checksum}"
"""

DOCKERFILE = """\
ARG VERSION=dev
ARG WEB_CLIENT_SHA={sha}

FROM builder AS page
ARG WEB_CLIENT_SHA
"""

README = """\
# Reference server

`v0.5.1` is the release this tree is at, and the page it serves is cut from
`web_client` at {sha}. Neither string is a home for a value.
"""

# What `cargo update --workspace` does to this workspace, and the whole of what
# the script may ask of cargo. Anything else fails, so a test that sees this run
# where it should not have knows.
STUB_CARGO = '''\
#!/usr/bin/env python3
import os
import re
import sys

log = os.environ.get("STUB_CARGO_LOG")
if log:
    with open(log, "a", encoding="utf-8") as handle:
        handle.write(" ".join(sys.argv[1:]) + "\\n")

if os.environ.get("STUB_CARGO_STATUS"):
    sys.exit(int(os.environ["STUB_CARGO_STATUS"]))

if sys.argv[1:2] != ["update"] or "--workspace" not in sys.argv:
    print("stub cargo implements `update --workspace` and nothing else", file=sys.stderr)
    sys.exit(1)

manifest = open("Cargo.toml", encoding="utf-8").read()
section = manifest.split("[workspace.package]", 1)[1]
version = os.environ.get("STUB_CARGO_LOCK_VERSION") or re.search(
    r'^version = "(.*)"$', section, re.MULTILINE
).group(1)

blocks = open("Cargo.lock", encoding="utf-8").read().split("[[package]]")
moved = []
for index, block in enumerate(blocks):
    if index and "source = " not in block:
        block = re.sub(r'(?m)^version = ".*"$', f'version = "{version}"', block)
    moved.append(block)
open("Cargo.lock", "w", encoding="utf-8").write("[[package]]".join(moved))
'''


class Repo:
    """A tree with the three files, a stand-in cargo on PATH, and a snapshot."""

    def __init__(self, root: Path, version: str = "0.5.1", sha: str = SHA):
        self.root = root
        self.repo = root / "repo"
        self.bin = root / "bin"
        self.log = root / "cargo.log"
        (self.repo / "scripts").mkdir(parents=True)
        self.bin.mkdir()
        shutil.copy(SCRIPT, self.repo / "scripts" / SCRIPT.name)
        self.write(version, sha)
        stub = self.bin / "cargo"
        # The stand-in is executed by the script through `PATH`, so its shebang
        # has to name this interpreter rather than `/usr/bin/env` for the same
        # reason.
        stub.write_text(f"#!{sys.executable}\n" + STUB_CARGO.split("\n", 1)[1], encoding="utf-8")
        stub.chmod(0o755)

    def write(self, version: str, sha: str) -> None:
        (self.repo / "Cargo.toml").write_text(MANIFEST.format(version=version), encoding="utf-8")
        (self.repo / "Cargo.lock").write_text(
            LOCK.format(version=version, checksum="a" * 64), encoding="utf-8"
        )
        (self.repo / "Dockerfile").write_text(DOCKERFILE.format(sha=sha), encoding="utf-8")
        (self.repo / "README.md").write_text(README.format(sha=sha), encoding="utf-8")

    def snapshot(self) -> dict:
        """Every path under the tree, and what a file there holds."""
        taken = {}
        for path in sorted(self.repo.rglob("*")):
            relative = str(path.relative_to(self.repo))
            taken[relative] = path.read_bytes() if path.is_file() else None
        return taken

    def run(self, *arguments, **environment):
        env = dict(os.environ)
        env["PATH"] = f"{self.bin}:{env['PATH']}"
        env["STUB_CARGO_LOG"] = str(self.log)
        env.update(environment)
        # Run through the shell that the shebang names rather than by the shebang:
        # a nix build sandbox has no `/usr/bin/env`, and what the installed name
        # needs is the exec bit and that line, which the last test asserts.
        return subprocess.run(
            [BASH, str(self.repo / "scripts" / SCRIPT.name), *arguments],
            cwd=self.repo,
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )

    def cargo_ran(self) -> bool:
        return self.log.exists() and self.log.read_text(encoding="utf-8") != ""

    def read(self, name: str) -> str:
        return (self.repo / name).read_text(encoding="utf-8")

    def carries(self, version: str, sha: str) -> bool:
        """Whether each value is in its own home, and only there."""
        section = self.read("Cargo.toml").split("[workspace.package]", 1)[1]
        manifest = re.search(r'(?m)^version = "(.*)"$', section).group(1)
        members = [
            re.search(r'(?m)^version = "(.*)"$', block).group(1)
            for block in self.read("Cargo.lock").split("[[package]]")[1:]
            if "source = " not in block
        ]
        return (
            manifest == version
            and members == [version, version]
            and re.search(r'(?m)^ARG WEB_CLIENT_SHA=(.*)$', self.read("Dockerfile")).group(1) == sha
        )


class RefusalTest(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.repo = Repo(Path(self.directory.name))
        self.before = self.repo.snapshot()

    def assert_refused(self, *arguments):
        done = self.repo.run(*arguments)
        self.assertEqual(done.returncode, 2, f"{arguments}: {done.stdout}{done.stderr}")
        self.assertIn("usage:", done.stderr)
        self.assertEqual(self.repo.snapshot(), self.before, "a refusal wrote to the tree")
        self.assertFalse(self.repo.cargo_ran(), "a refusal reached cargo")
        return done

    def test_a_version_that_is_not_x_y_z_is_refused(self):
        for version in ("1.2", "v1.2.3", "1.2.3-rc1", "1.2.3+build", "1.2.3.4", "01.2.3", "0.6.0.", "x.y.z", "0.6.0 ", "0.6.0\n", ""):
            with self.subTest(version=version):
                self.assert_refused(version, "--page-sha", SHA)

    def test_no_version_at_all_is_refused(self):
        self.assert_refused()
        self.assert_refused("--page-sha", SHA)

    def test_a_page_sha_that_is_not_40_lowercase_hex_is_refused(self):
        for sha in ("", "abc", SHA[:-1], SHA + "a", SHA.upper(), SHA.replace("a", "g"), "0x" + SHA, SHA + " "):
            with self.subTest(sha=sha):
                self.assert_refused("0.6.0", "--page-sha", sha)

    def test_page_sha_is_required(self):
        """Refused for being absent, not for being a bad sha: the caller is told which."""
        self.assertIn("--page-sha is required", self.assert_refused("0.6.0").stderr)
        self.assert_refused("0.6.0", "--page")
        self.assert_refused("0.6.0", "--page-sha")

    def test_an_unknown_option_and_a_second_version_are_refused(self):
        self.assert_refused("0.6.0", "--page-sha", SHA, "--force")
        self.assert_refused("0.6.0", "0.6.1", "--page-sha", SHA)
        self.assert_refused("0.6.0", "--page-sha", SHA, SHA)

    def test_the_page_sha_cannot_be_given_twice(self):
        self.assert_refused("0.6.0", "--page-sha", SHA, "--page-sha", OTHER_SHA)


class NoOpTest(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.repo = Repo(Path(self.directory.name))

    def test_a_tree_that_carries_both_values_is_left_untouched(self):
        before = self.repo.snapshot()
        done = self.repo.run("0.5.1", "--page-sha", SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertIn("already at 0.5.1", done.stdout)
        self.assertIn("nothing changed", done.stdout)
        self.assertNotIn("changed:", done.stdout)
        self.assertEqual(self.repo.snapshot(), before)
        self.assertFalse(self.repo.cargo_ran())


class WriteTest(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.repo = Repo(Path(self.directory.name))

    def test_the_version_and_the_sha_move_together(self):
        before = self.repo.snapshot()
        done = self.repo.run("0.6.0", "--page-sha", OTHER_SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        for line in ("changed: Cargo.toml", "changed: Cargo.lock", "changed: Dockerfile"):
            self.assertIn(line, done.stdout)
        self.assertTrue(self.repo.carries("0.6.0", OTHER_SHA))
        self.assertTrue(self.repo.cargo_ran())
        # Nothing was added, removed or renamed: the set of files is the one it was.
        after = self.repo.snapshot()
        self.assertEqual(sorted(after), sorted(before))
        moved = {name for name in before if before[name] != after[name]}
        self.assertEqual(moved, {"Cargo.toml", "Cargo.lock", "Dockerfile"})

    def test_the_registry_package_in_the_lock_does_not_move(self):
        self.repo.run("0.6.0", "--page-sha", OTHER_SHA)
        self.assertIn('name = "serde"\nversion = "1.0.219"', self.repo.read("Cargo.lock"))

    def test_prose_naming_a_version_is_not_a_home_for_it(self):
        before = self.repo.read("README.md")
        self.repo.run("0.6.0", "--page-sha", OTHER_SHA)
        self.assertEqual(self.repo.read("README.md"), before)

    def test_a_stale_lock_alone_is_regenerated(self):
        (self.repo.repo / "Cargo.lock").write_text(
            LOCK.format(version="0.5.0", checksum="a" * 64), encoding="utf-8"
        )
        manifest = self.repo.read("Cargo.toml")
        done = self.repo.run("0.5.1", "--page-sha", SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertIn("changed: Cargo.lock", done.stdout)
        self.assertNotIn("changed: Cargo.toml", done.stdout)
        self.assertNotIn("changed: Dockerfile", done.stdout)
        self.assertEqual(self.repo.read("Cargo.toml"), manifest)
        self.assertTrue(self.repo.carries("0.5.1", SHA))

    def test_a_dockerfile_that_already_carries_the_sha_is_not_rewritten(self):
        dockerfile = self.repo.read("Dockerfile")
        lock = self.repo.read("Cargo.lock")
        done = self.repo.run("0.6.0", "--page-sha", SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(
            sorted(line for line in done.stdout.splitlines() if line.startswith("changed:")),
            ["changed: Cargo.lock", "changed: Cargo.toml"],
        )
        self.assertEqual(self.repo.read("Dockerfile"), dockerfile)
        self.assertNotEqual(self.repo.read("Cargo.lock"), lock)
        self.assertTrue(self.repo.carries("0.6.0", SHA))

    def test_a_manifest_and_lock_that_already_carry_the_version_are_not_rewritten(self):
        manifest = self.repo.read("Cargo.toml")
        lock = self.repo.read("Cargo.lock")
        done = self.repo.run("0.5.1", "--page-sha", OTHER_SHA)
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual([line for line in done.stdout.splitlines() if line.startswith("changed:")], ["changed: Dockerfile"])
        self.assertEqual(self.repo.read("Cargo.toml"), manifest)
        self.assertEqual(self.repo.read("Cargo.lock"), lock)
        self.assertFalse(self.repo.cargo_ran(), "the version did not move, so cargo had nothing to do")
        self.assertTrue(self.repo.carries("0.5.1", OTHER_SHA))

    def test_a_cargo_that_fails_leaves_the_tree_it_started_with(self):
        before = self.repo.snapshot()
        done = self.repo.run("0.6.0", "--page-sha", OTHER_SHA, STUB_CARGO_STATUS="1")
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn("cargo update --workspace failed", done.stderr)
        self.assertEqual(self.repo.snapshot(), before, "a failed cargo left a bumped tree")
        self.assertTrue(self.repo.cargo_ran())

    def test_a_cargo_that_leaves_the_lock_wrong_is_refused_and_the_tree_restored(self):
        """A lock cargo did not bring into line is caught here, not by a release build."""
        before = self.repo.snapshot()
        done = self.repo.run("0.6.0", "--page-sha", OTHER_SHA, STUB_CARGO_LOCK_VERSION="0.5.1")
        self.assertEqual(done.returncode, 1, done.stdout + done.stderr)
        self.assertIn("Cargo.lock does not carry 0.6.0", done.stderr)
        self.assertEqual(self.repo.snapshot(), before)

    def test_the_second_run_of_the_same_version_is_a_no_op(self):
        self.assertEqual(self.repo.run("0.6.0", "--page-sha", OTHER_SHA).returncode, 0)
        after = self.repo.snapshot()
        self.repo.log.unlink()
        again = self.repo.run("0.6.0", "--page-sha", OTHER_SHA)
        self.assertEqual(again.returncode, 0, again.stdout + again.stderr)
        self.assertIn("already at 0.6.0", again.stdout)
        self.assertEqual(self.repo.snapshot(), after)
        self.assertFalse(self.repo.cargo_ran())


class InstallationTest(unittest.TestCase):
    """The script is installed as a program, so the tracked file is executable."""

    def test_the_script_is_executable_and_has_a_shebang(self):
        self.assertTrue(os.access(SCRIPT, os.X_OK), SCRIPT)
        self.assertEqual(SCRIPT.read_bytes().split(b"\n", 1)[0], b"#!/usr/bin/env bash")


if __name__ == "__main__":
    unittest.main(verbosity=2)
